name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_to_registry:
    runs-on: [self-hosted,linux,X64]
    # Set enviroment variables  
    env:
     AZURE_CR: "thomastestazurecontainerreg.azurecr.io"
     IMG_TAG: $GITHUB_SHA
     IMAGE_NAME: "flask-hello-world-app"
     
    steps: 
# Checkout the repository
    - id: checkout_repo
      name: Check out the repo
      uses: actions/checkout@v2

#----------------------------------
# Build the container image for DockerHub
    - id: build_container_dockerhub
      name: Build the Docker image
      run: docker build --file amd64.Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMG_NAME:$IMG_TAG .

# Login to Dockerhub
    - id: login_dockerhub
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# Push the built Docker image to the Dockerhub registry
    - id: push_dockerhub
      name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMG_NAME:$IMG_TAG
      
#----------------------------------
# Build the container image for DockerHub
    - id: build_container_azure
      name: Build the Docker image (cache will be used and just another tag wil be applied!)
      run: docker build --file amd64.Dockerfile --tag $AZURE_CR/$IMG_NAME:$IMG_TAG .
      
# Push the built Docker image to the Dockerhub registry
    - id: push_azure
      name: Push image to Azure container registry
      run: docker push $AZURE_CR/$IMG_NAME:$IMG_TAG
#----------------------------------

