name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted, linux, ARM]

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file arm32v7.Dockerfile --tag flask-hello-world-app:$GITHUB_SHA
    
    - name: Push image to DockerHub
      run: docker push thomaspilz/flask-hello-world-app:$(GITHUB_SHA)
