name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_to_registry:
    runs-on: [self-hosted, linux, ARM]
#
#    runs-on: ubuntu-latest
#
    steps:
#    - name: Check out the repo
#      uses: actions/checkout@v2
#    
#    - name: Push to Docker Hub
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#        repository: thomaspilz/flask-hello-world-app
#        tags: $GITHUB_SHA

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build --file arm32v7.Dockerfile --tag thomaspilz/flask-hello-world-app:$GITHUB_SHA .
    
    - name: Push image to DockerHub
      run: docker push thomaspilz/flask-hello-world-app:$GITHUB_SHA
